[project]
top_name = "mobilenet_v2"
onnx_path = "/workspace/NN2FPGA/models/onnx/mobilenet_v2_a8w8b16_71.734.onnx"
project_root = "/workspace/NN2FPGA/work/mobilenet_v2"

[platform]
board = "ZCU102"
frequency = 200

[options]
silvia_packing = true
