[project]
top_name = "yolov9t"
onnx_path = "/workspace/NN2FPGA/models/onnx/yolov9t_a8w8b32_po2.onnx"
project_root = "/workspace/NN2FPGA/work/yolov9t"
hls_version = 2025.1

[platform]
board = "ZCU102"
frequency = 200

[steps]
OptimizeBitwidth = true
AddStreamingParams = true
ComputeFifoDepth = true
Simulate = true
Deploy = false

[options]
silvia_packing = true
dsp_limit = 2000
