import numpy as np
import base64
import os
import subprocess
from backend.core.acceleratorpackage import AcceleratorPackage
from backend.util.board_util import read_board_info
from backend.util.codegen_utils import NewCodeWriter, cpp_function, cpp_variable, get_hls_quant_type, get_cpp_quant_type
from backend.core.tensor_quant import TensorQuant

def dump_tcl_script(top_name, part_name, frequency, hls_version, input_files):
    """Dump a TCL script to set up the HLS project and run the simulation."""

    argv = " ".join(input_files)
    tb_files = " ".join(input_files + ["testbench.cpp"])
    t_clk = f"{1e3 / int(frequency):.2f}ns" # Convert frequency in MHz to clock period in ns
    lines = list()
    lines.append("# Auto-generated TCL script for HLS project setup")
    lines.append("# Generated by nn2fpga simulation flow")
    lines.append("")

    # Check the HLS version to determine the correct syntax
    if float(hls_version) > 2025:
        lines.append(
            'open_component -reset "proj_{top_name}" -flow_target vivado',
        )
    else:
        lines.extend(
            [
                'open_project -reset "proj_{top_name}"',
                'open_solution -reset solution0',
            ]
        )

    lines.extend(
        [
            'add_files kernel.cpp -cflags " -I/workspace/NN2FPGA/nn2fpga/library/include"',
            'add_files -tb "/workspace/NN2FPGA/deps/cnpy/cnpy.cpp"',
            'add_files -tb "{tb_files}" -cflags "-I/workspace/NN2FPGA/deps/cnpy -I/workspace/NN2FPGA/nn2fpga/library/include -lz"',
            'set_top "{top_name}"',
            'set_part {part_name}',
            'create_clock -period {t_clk}',
            'csim_design -argv "{argv}"',
            'csynth_design',
            'cosim_design -argv "{argv}"',
            'exit',
        ]
    )

    return "\n".join(lines).format(
        top_name=top_name, tb_files=tb_files, part_name=part_name, t_clk=t_clk, argv=argv
    )

def generate_hls_driver(top_name, input_map, output_map, axi_bitwidth) -> str:
    """Generate HLS driver code for the given model.
    Args:
        model (ModelWrapper): The model to generate HLS driver code for.
    Returns:
        str: The generated HLS driver code as a string.
    """
    cwr = NewCodeWriter()
    cwr.add_autogen_comment()

    # Include sections for HLS
    cwr.include("ap_int.h")
    cwr.include("hls_stream.h")
    cwr.include("hls_vector.h")
    cwr.include("ap_axi_sdata.h")
    cwr.include("utils/testbench_utils.hpp")

    # Accelerator kernel function definition
    kernel_function = cpp_function(
        name=top_name,
        return_type="void",
        qualifiers=["extern"],
    )
    kernel_arguments = []

    for value in input_map.values():
        var = cpp_variable(
            value["new_name"],
            f"hls::stream<ap_axiu<{axi_bitwidth}, 0, 0, 0>>&",
        )
        kernel_function.add_argument(var)
        kernel_arguments.append(value["new_name"])

    for output in output_map.values():
        var = cpp_variable(
            output["new_name"],
            f"hls::stream<ap_axiu<{axi_bitwidth}, 0, 0, 0>>&",
        )
        kernel_function.add_argument(var)
        kernel_arguments.append(output["new_name"])

    # Add the function prototype, which will be called from the main function.
    cwr.add_function_prototype(kernel_function)

    # Main testbench function definition
    main_function = cpp_function(
        name="main",
        return_type="int",
        arguments=[cpp_variable("argc", "int"), cpp_variable("argv", "char**")],
    )

    # Add file and streams declarations
    file_arg_idx = 1
    file_map = {}
    for value in input_map.values():
        file_name = "file_" + value["new_name"]
        main_function.add_code(f"std::string {file_name} = argv[{file_arg_idx}];")
        var = cpp_variable(
            value["new_name"],
            f"hls::stream<ap_axiu<{axi_bitwidth}, 0, 0, 0>>",
        )
        main_function.add_code(f"{var.generate_declaration()};")
        file_arg_idx += 1

    for value in output_map.values():
        file_name = "file_" + value["new_name"]
        main_function.add_code(f"std::string {file_name} = argv[{file_arg_idx}];")
        var = cpp_variable(
            value["new_name"],
            f"hls::stream<ap_axiu<{axi_bitwidth}, 0, 0, 0>>",
        )
        main_function.add_code(f"{var.generate_declaration()};")
        file_arg_idx += 1

    # Add read from file calls for input streams
    for value in input_map.values():
        npy_read = cpp_function(
            name=f"npy_to_hls_stream",
            return_type="void",
            templates=["typename TAxi", "typename TData", "typename TDataNumpy"],
            arguments=[
                ("input_path", "std::string"),
                (f"stream", f"hls::stream<TAxi>&"),
                ("data_per_word", "int"),
            ],
        )

        tensor_quant = TensorQuant.from_canonical_name(value["quant"])
        data_per_word = axi_bitwidth // int(tensor_quant.bitwidth)

        main_function.add_code(
            npy_read.generate_call(
                [
                    f"ap_axiu<{axi_bitwidth}, 0, 0, 0>",
                    get_hls_quant_type(tensor_quant),
                    get_cpp_quant_type(tensor_quant),
                ],
                f"file_{value['new_name']}",
                value["new_name"],
                str(data_per_word),
            ) + ";"
        )

    # Add the kernel function call
    main_function.add_code(f"{kernel_function.generate_call([], *kernel_arguments)};")

    # Add write to file calls for output streams
    for value in output_map.values():
        npy_write = cpp_function(
            name=f"hls_stream_to_npy",
            return_type="void",
            templates=["typename TAxi", "typename TData", "typename TDataNumpy"],
            arguments=[
                ("input_path", "std::string"),
                (f"stream", f"hls::stream<TAxi>&"),
                ("data_per_word", "int"),
                ("shape", "const std::vector<size_t>&"),
            ],
        )

        tensor_quant = TensorQuant.from_canonical_name(value["quant"])
        data_per_word = axi_bitwidth // int(tensor_quant.bitwidth)
        shape_str = str(value["shape"]).replace("[", "{").replace("]", "}")

        main_function.add_code(
            npy_write.generate_call(
                [
                    f"ap_axiu<{axi_bitwidth}, 0, 0, 0>",
                    get_hls_quant_type(tensor_quant),
                    get_cpp_quant_type(tensor_quant),
                ],
                f"file_{value['new_name']}",
                value["new_name"],
                str(data_per_word),
                shape_str,
            ) + ";"
        )

    main_function.add_code("return 0;")
    cwr.add_function_definition(main_function)
    return cwr.code

def make_build_dir(work_dir: str) -> None:
    """Create the working directory for the simulation."""
    os.makedirs(work_dir, exist_ok=True)

def simulate(accelerator_package_serialized: str, context: dict) -> dict:

    ap = AcceleratorPackage.from_json(accelerator_package_serialized)
    work_dir = ap.work_dir
    work_dir = f"{os.path.abspath(work_dir)}/sim"
    make_build_dir(work_dir)
    internal_context = list()
    input_list = list()
    output_list = list()

    # Update the context with the input map
    input_map = ap.input_map
    for old_name, value in input_map.items():
        new_name = value["new_name"]
        if old_name in context:
            internal_context.append((new_name, context[old_name]))
        elif value['value'] is not None:
            internal_context.append((new_name, np.frombuffer(base64.b64decode(value['value']), dtype=np.uint32).reshape(value['shape'])))
        else:
            raise ValueError(f"Input {old_name} not found in context and no default value provided.")
    input_list.extend([value["new_name"] for value in input_map.values()])

    # Update the context with the output map
    output_map = ap.output_map
    for old_name, value in output_map.items():
        new_name = value["new_name"]
        if old_name in context:
            internal_context.append((new_name, context[old_name]))
    output_list.extend([value["new_name"] for value in output_map.values()])

    # Save to file the internal context
    for tensor_name, tensor_data in internal_context:
        np.save(f"{work_dir}/{tensor_name}.npy", tensor_data)

    # Generate the TCL script
    board_info = read_board_info(ap.board_name)
    tcl_script = dump_tcl_script(
        top_name=ap.top_name,
        part_name=board_info["part"],
        frequency=ap.frequency,
        hls_version=ap.hls_version,
        input_files=[f"{work_dir}/{tensor_name}.npy" for tensor_name, _ in internal_context],
    )

    # Write the TCL script to a file
    with open(f"{work_dir}/setup.tcl", "w") as f:
        f.write(tcl_script)

    # Write the HLS code to a file
    with open(f"{work_dir}/kernel.cpp", "w") as f:
        f.write(base64.b64decode(ap.hls_code_b64).decode())

    # Generate the HLS driver code
    with open(f"{work_dir}/testbench.cpp", "w") as f:
        f.write(generate_hls_driver(
            top_name=ap.top_name,
            input_map=ap.input_map,
            output_map=ap.output_map,
            axi_bitwidth=int(board_info["axi_bitwidth"]),
        ))

    # run the simulation
    subprocess.run(
        ["vitis_hls", "-f", f"{work_dir}/setup.tcl"],
        cwd=work_dir,
        check=True
    )

    # Read the output files and update the context
    for old_name, value in output_map.items():
        output_file = f"{work_dir}/{value['new_name']}.npy"
        if os.path.exists(output_file):
            tensor_data = np.load(output_file)
            context[old_name] = tensor_data
        else:
            raise FileNotFoundError(f"Output file {output_file} not found.")
    
    # Erase the simulation directory if everything went well
    if os.path.exists(work_dir):
        subprocess.run(["rm", "-rf", work_dir], check=True)

    return context
