[project]
top_name = "resnet20"
onnx_path = "/workspace/NN2FPGA/models/onnx/resnet20_a8w8b16.onnx"
project_root = "/workspace/NN2FPGA/work/resnet20"
hls_version = 2025.2

[platform]
board = "KRIA"
frequency = 250

[steps]
OptimizeBitwidth = true
AddStreamingParams = true
ComputeFifoDepth = true
Simulate = true
Deploy = true

[options]
silvia_packing = true
